# Generated by Django 4.2.3 on 2023-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_event_type_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Booked', 'Booked')], default='Pending', max_length=250),
        ),
    ]
