# Generated by Django 4.2.3 on 2023-08-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=250),
        ),
    ]
